import "./styles/globals.css";

export const metadata = {
  title: "Black Hole",
  description: "Computer generated by Sebastian Fok",
  icons: {
    icon: "/images/BHIcon.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{padding:"0", margin:"0"}}>
      <body>
        {children}
      </body>
    </html>
  );
}
